In [1]:
# Pytorch Basics 

In [ ]:
import torch

In [6]:
# Number
t1 = torch.tensor(2.)
t1


tensor(2.)

In [5]:
t1.dtype

torch.float32

In [7]:
# Vector
t2 = torch.tensor([1., 2., 3, 4])
t2

tensor([1., 2., 3., 4.])

In [8]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [10]:
# 3-dimensional array
t4 = torch.tensor([
    [[21, 22, 23], 
     [23, 24, 25]], 
    [[25, 26, 27], 
     [27, 28, 29.]]])
t4

tensor([[[21., 22., 23.],
         [23., 24., 25.]],

        [[25., 26., 27.],
         [27., 28., 29.]]])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
#Basic Auto grad example 1

In [17]:
#Basic Autograd Example
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [18]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 


tensor(2.)
tensor(1.)
tensor(1.)


In [19]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: tensor(2.)
dy/dw: tensor(1.)
dy/db: tensor(1.)


In [23]:
#Basic Auto grad example 2

In [24]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [26]:
# Build a fully connected layer.
import torch.nn as nn 
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.2952, -0.1433,  0.3021],
        [-0.5628, -0.3223,  0.5685]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.0969, -0.3935], requires_grad=True)


In [27]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [28]:
# Forward pass.
pred = linear(x)

In [29]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  0.9510029554367065


In [30]:
# Backward pass.
loss.backward()

In [31]:
# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.2379,  0.8574,  0.7902],
        [-0.2352,  0.3811,  0.3544]])
dL/db:  tensor([0.6118, 0.0326])


In [32]:
# 1-step gradient descent.
optimizer.step()

In [33]:
# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  0.9300593137741089


In [ ]:
#Pytorch interopretability with numpy

In [20]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [21]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [22]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])